name: Build & Deploy Superset

on:
  push:
    branches:
      - custom-6.0.0
  workflow_dispatch:

env:
  IMAGE_NAME: superset
  ACR_LOGIN_SERVER: acrreportingprod.azurecr.io

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tag.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: tag
        run: |
          TAG=${GITHUB_SHA::7}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name acrreportingprod

      - name: Build image
        run: |
          docker build \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ steps.tag.outputs.tag }} \
            .

      - name: Push image
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ steps.tag.outputs.tag }}

  deploy_qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: build
    environment: qa

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy QA
        run: |
          az containerapp update \
            --name gfn-superset-qa \
            --resource-group grp-reporting-prod-eastus \
            --container-name gfn-superset-qa \
            --image $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ needs.build.outputs.image_tag }}

  deploy_prod:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    needs: deploy_qa
    environment: prod

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy PROD
        run: |
          az containerapp update \
            --name gfn-superset-prod \
            --resource-group grp-reporting-prod-eastus \
            --container-name gfn-superset-prod \
            --image $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ needs.build.outputs.image_tag }}
